/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6459edd35024
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { TeiwahError } from "./teiwah-error.js";

/**
 * Gateway errors may contain only `message`; Nest errors generally also
 *
 * @remarks
 * contain `statusCode` and `error`. Validation errors may return an array
 * of messages.
 */
export type ErrorResponseData = {
  statusCode?: number | undefined;
  message: models.Message;
  error?: string | undefined;

  [additionalProperties: string]: unknown;
};

/**
 * Gateway errors may contain only `message`; Nest errors generally also
 *
 * @remarks
 * contain `statusCode` and `error`. Validation errors may return an array
 * of messages.
 */
export class ErrorResponse extends TeiwahError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorResponseData;

  constructor(
    err: ErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err["message"] === "string"
      ? err["message"]
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "ErrorResponse";
  }
}

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodMiniType<
  ErrorResponse,
  unknown
> = z.pipe(
  z.object({
    statusCode: z.optional(z.int()),
    message: z.lazy(() => models.Message$inboundSchema),
    error: z.optional(z.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export type ErrorResponse$Outbound = {
  statusCode?: number | undefined;
  message: models.Message$Outbound;
  error?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ErrorResponse$outboundSchema: z.ZodMiniType<
  ErrorResponse$Outbound,
  ErrorResponse
> = z.pipe(
  z.pipe(
    z.custom<ErrorResponse>(x => x instanceof ErrorResponse),
    z.transform(v => v.data$),
  ),
  z.catchall(
    z.object({
      statusCode: z.optional(z.int()),
      message: z.lazy(() => models.Message$outboundSchema),
      error: z.optional(z.string()),
    }),
    z.any(),
  ),
);
