/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 22da4bda1d7a
 */

import { chatActionsMarkMessageRead } from "../funcs/chat-actions-mark-message-read.js";
import { chatActionsSendTypingIndicator } from "../funcs/chat-actions-send-typing-indicator.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ChatActions extends ClientSDK {
  /**
   * Show the typing indicator
   *
   * @remarks
   * Shows the WhatsApp typing indicator for a conversation. Call this shortly
   * before replying. There is no stop operation; WhatsApp clears the indicator
   * automatically after roughly 25 seconds or when a message is sent.
   */
  async sendTypingIndicator(
    request: models.TypingRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(chatActionsSendTypingIndicator(
      this,
      request,
      options,
    ));
  }

  /**
   * Mark an inbound message as read
   *
   * @remarks
   * Sends a WhatsApp read receipt for an inbound message. Supply the native
   * `id` from the webhook as `messageId`. Teiwah resolves the full WhatsApp
   * message key from its recent-message cache.
   */
  async markMessageRead(
    request: models.ReadRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(chatActionsMarkMessageRead(
      this,
      request,
      options,
    ));
  }
}
