/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e591d523b9e9
 */

import { mediaDownloadMedia } from "../funcs/media-download-media.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Media extends ClientSDK {
  /**
   * Download inbound media
   *
   * @remarks
   * Downloads and decrypts media referenced by an inbound webhook. Use the
   * media message's native `id`, which is also the final path segment in the
   * webhook's `media.url`.
   *
   * The response Content-Type is the original media type when available and
   * Content-Disposition contains the original or derived filename.
   */
  async downloadMedia(
    request: operations.DownloadMediaRequest,
    options?: RequestOptions,
  ): Promise<operations.DownloadMediaResponse> {
    return unwrapAsync(mediaDownloadMedia(
      this,
      request,
      options,
    ));
  }
}
