/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 89df5fa2bb12
 */

import { messagesSendMessage } from "../funcs/messages-send-message.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Messages extends ClientSDK {
  /**
   * Send a message
   *
   * @remarks
   * Sends a text or media message from the WhatsApp session identified by
   * the API key.
   *
   * `quoteMessageId` may reference an inbound message ID or the ID returned
   * by an earlier send. Quoting is best-effort: if the ID is unknown or has
   * left the recent-message cache, the message is sent without a quote.
   *
   * A cold one-to-one send to a contact who has not previously engaged the
   * connected account is rejected with 403. Group sends are not subject to
   * this trusted-contact restriction.
   *
   * Clients must not automatically retry this operation. A transport or
   * server failure can be ambiguous: WhatsApp may have accepted the message
   * even when Teiwah could not return a usable response.
   */
  async sendMessage(
    request: models.SendMessageRequest,
    options?: RequestOptions,
  ): Promise<models.SendMessageResponse> {
    return unwrapAsync(messagesSendMessage(
      this,
      request,
      options,
    ));
  }
}
