/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 784571af2f69
 */

import { ClientSDK } from "../lib/sdks.js";
import { ChatActions } from "./chat-actions.js";
import { Media } from "./media.js";
import { Messages } from "./messages.js";

export class Teiwah extends ClientSDK {
  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _chatActions?: ChatActions;
  get chatActions(): ChatActions {
    return (this._chatActions ??= new ChatActions(this._options));
  }

  private _media?: Media;
  get media(): Media {
    return (this._media ??= new Media(this._options));
  }
}
