/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: af7143d12f4d
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the teiwah SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx messagesSendMessage.example.ts
 */

import { Teiwah } from "teiwah";

const teiwah = new Teiwah({
  apiKey: process.env["TEIWAH_API_KEY"] ?? "",
});

async function main() {
  const result = await teiwah.sendText({
    chatId: "972501234567",
    text: "Hello from Teiwah",
  });

  console.log(result);
}

main().catch(console.error);
