/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 543f3adbafd9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DownloadMediaRequest = {
  /**
   * Native ID of an inbound media message.
   */
  id: string;
};

export type DownloadMediaResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export const DownloadMediaRequest$inboundSchema: z.ZodMiniType<
  DownloadMediaRequest,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type DownloadMediaRequest$Outbound = {
  id: string;
};

/** @internal */
export const DownloadMediaRequest$outboundSchema: z.ZodMiniType<
  DownloadMediaRequest$Outbound,
  DownloadMediaRequest
> = z.object({
  id: z.string(),
});

export function downloadMediaRequestToJSON(
  downloadMediaRequest: DownloadMediaRequest,
): string {
  return JSON.stringify(
    DownloadMediaRequest$outboundSchema.parse(downloadMediaRequest),
  );
}
export function downloadMediaRequestFromJSON(
  jsonString: string,
): SafeParseResult<DownloadMediaRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadMediaRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadMediaRequest' from JSON`,
  );
}

/** @internal */
export const DownloadMediaResponse$inboundSchema: z.ZodMiniType<
  DownloadMediaResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.custom<ReadableStream<Uint8Array>>(x =>
      x instanceof ReadableStream
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);
/** @internal */
export type DownloadMediaResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ReadableStream<Uint8Array>;
};

/** @internal */
export const DownloadMediaResponse$outboundSchema: z.ZodMiniType<
  DownloadMediaResponse$Outbound,
  DownloadMediaResponse
> = z.pipe(
  z.object({
    headers: z.record(z.string(), z.array(z.string())),
    result: z.custom<ReadableStream<Uint8Array>>(x =>
      x instanceof ReadableStream
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  }),
);

export function downloadMediaResponseToJSON(
  downloadMediaResponse: DownloadMediaResponse,
): string {
  return JSON.stringify(
    DownloadMediaResponse$outboundSchema.parse(downloadMediaResponse),
  );
}
export function downloadMediaResponseFromJSON(
  jsonString: string,
): SafeParseResult<DownloadMediaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadMediaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadMediaResponse' from JSON`,
  );
}
