/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a1828112515
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Message = string | Array<string>;

/** @internal */
export const Message$inboundSchema: z.ZodMiniType<Message, unknown> =
  smartUnion([z.string(), z.array(z.string())]);
/** @internal */
export type Message$Outbound = string | Array<string>;

/** @internal */
export const Message$outboundSchema: z.ZodMiniType<Message$Outbound, Message> =
  smartUnion([z.string(), z.array(z.string())]);

export function messageToJSON(message: Message): string {
  return JSON.stringify(Message$outboundSchema.parse(message));
}
export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}
