/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 873d22b512dc
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * `ptt` is a WhatsApp voice note; `audio` is a generic audio attachment.
 */
export const MediaType = {
  Image: "image",
  Ptt: "ptt",
  Audio: "audio",
  Video: "video",
  Document: "document",
} as const;
/**
 * `ptt` is a WhatsApp voice note; `audio` is a generic audio attachment.
 */
export type MediaType = ClosedEnum<typeof MediaType>;

/** @internal */
export const MediaType$inboundSchema: z.ZodMiniEnum<typeof MediaType> = z.enum(
  MediaType,
);
/** @internal */
export const MediaType$outboundSchema: z.ZodMiniEnum<typeof MediaType> =
  MediaType$inboundSchema;
