/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 84748ccfbcd7
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MediaType,
  MediaType$inboundSchema,
  MediaType$outboundSchema,
} from "./media-type.js";

export type OutboundMediaByBase64 = {
  /**
   * `ptt` is a WhatsApp voice note; `audio` is a generic audio attachment.
   */
  type: MediaType;
  /**
   * Plain base64-encoded bytes, limited to 16 MB after decoding. Data URIs are not accepted.
   */
  base64: string;
  /**
   * Optional caption, primarily for image, video, and document messages.
   */
  caption?: string | undefined;
  /**
   * Optional MIME type used when staging the temporary media object.
   */
  mimeType?: string | undefined;
  /**
   * Optional filename, primarily for document messages.
   */
  filename?: string | undefined;
};

/** @internal */
export const OutboundMediaByBase64$inboundSchema: z.ZodMiniType<
  OutboundMediaByBase64,
  unknown
> = z.object({
  type: MediaType$inboundSchema,
  base64: z.string(),
  caption: z.optional(z.string()),
  mimeType: z.optional(z.string()),
  filename: z.optional(z.string()),
});
/** @internal */
export type OutboundMediaByBase64$Outbound = {
  type: string;
  base64: string;
  caption?: string | undefined;
  mimeType?: string | undefined;
  filename?: string | undefined;
};

/** @internal */
export const OutboundMediaByBase64$outboundSchema: z.ZodMiniType<
  OutboundMediaByBase64$Outbound,
  OutboundMediaByBase64
> = z.object({
  type: MediaType$outboundSchema,
  base64: z.string(),
  caption: z.optional(z.string()),
  mimeType: z.optional(z.string()),
  filename: z.optional(z.string()),
});

export function outboundMediaByBase64ToJSON(
  outboundMediaByBase64: OutboundMediaByBase64,
): string {
  return JSON.stringify(
    OutboundMediaByBase64$outboundSchema.parse(outboundMediaByBase64),
  );
}
export function outboundMediaByBase64FromJSON(
  jsonString: string,
): SafeParseResult<OutboundMediaByBase64, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutboundMediaByBase64$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutboundMediaByBase64' from JSON`,
  );
}
