/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: afcae1bbba18
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OutboundMediaByBase64,
  OutboundMediaByBase64$inboundSchema,
  OutboundMediaByBase64$Outbound,
  OutboundMediaByBase64$outboundSchema,
} from "./outbound-media-by-base64.js";
import {
  OutboundMediaByUrl,
  OutboundMediaByUrl$inboundSchema,
  OutboundMediaByUrl$Outbound,
  OutboundMediaByUrl$outboundSchema,
} from "./outbound-media-by-url.js";

/**
 * Supply exactly one URL or base64 source.
 */
export type OutboundMedia = OutboundMediaByUrl | OutboundMediaByBase64;

/** @internal */
export const OutboundMedia$inboundSchema: z.ZodMiniType<
  OutboundMedia,
  unknown
> = smartUnion([
  OutboundMediaByUrl$inboundSchema,
  OutboundMediaByBase64$inboundSchema,
]);
/** @internal */
export type OutboundMedia$Outbound =
  | OutboundMediaByUrl$Outbound
  | OutboundMediaByBase64$Outbound;

/** @internal */
export const OutboundMedia$outboundSchema: z.ZodMiniType<
  OutboundMedia$Outbound,
  OutboundMedia
> = smartUnion([
  OutboundMediaByUrl$outboundSchema,
  OutboundMediaByBase64$outboundSchema,
]);

export function outboundMediaToJSON(outboundMedia: OutboundMedia): string {
  return JSON.stringify(OutboundMedia$outboundSchema.parse(outboundMedia));
}
export function outboundMediaFromJSON(
  jsonString: string,
): SafeParseResult<OutboundMedia, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutboundMedia$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutboundMedia' from JSON`,
  );
}
