/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1fba6563ed43
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MediaType,
  MediaType$inboundSchema,
  MediaType$outboundSchema,
} from "./media-type.js";

export type OutboundMediaByUrl = {
  /**
   * `ptt` is a WhatsApp voice note; `audio` is a generic audio attachment.
   */
  type: MediaType;
  /**
   * Publicly fetchable media URL.
   */
  url: string;
  /**
   * Optional caption, primarily for image, video, and document messages.
   */
  caption?: string | undefined;
  /**
   * Optional MIME override; normally inferred from the URL or content.
   */
  mimeType?: string | undefined;
  /**
   * Optional filename, primarily for document messages.
   */
  filename?: string | undefined;
};

/** @internal */
export const OutboundMediaByUrl$inboundSchema: z.ZodMiniType<
  OutboundMediaByUrl,
  unknown
> = z.object({
  type: MediaType$inboundSchema,
  url: z.string(),
  caption: z.optional(z.string()),
  mimeType: z.optional(z.string()),
  filename: z.optional(z.string()),
});
/** @internal */
export type OutboundMediaByUrl$Outbound = {
  type: string;
  url: string;
  caption?: string | undefined;
  mimeType?: string | undefined;
  filename?: string | undefined;
};

/** @internal */
export const OutboundMediaByUrl$outboundSchema: z.ZodMiniType<
  OutboundMediaByUrl$Outbound,
  OutboundMediaByUrl
> = z.object({
  type: MediaType$outboundSchema,
  url: z.string(),
  caption: z.optional(z.string()),
  mimeType: z.optional(z.string()),
  filename: z.optional(z.string()),
});

export function outboundMediaByUrlToJSON(
  outboundMediaByUrl: OutboundMediaByUrl,
): string {
  return JSON.stringify(
    OutboundMediaByUrl$outboundSchema.parse(outboundMediaByUrl),
  );
}
export function outboundMediaByUrlFromJSON(
  jsonString: string,
): SafeParseResult<OutboundMediaByUrl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutboundMediaByUrl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutboundMediaByUrl' from JSON`,
  );
}
