/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8755dc32474f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ReadRequest = {
  /**
   * Native WhatsApp/Baileys message identifier.
   */
  messageId: string;
};

/** @internal */
export const ReadRequest$inboundSchema: z.ZodMiniType<ReadRequest, unknown> = z
  .object({
    messageId: z.string(),
  });
/** @internal */
export type ReadRequest$Outbound = {
  messageId: string;
};

/** @internal */
export const ReadRequest$outboundSchema: z.ZodMiniType<
  ReadRequest$Outbound,
  ReadRequest
> = z.object({
  messageId: z.string(),
});

export function readRequestToJSON(readRequest: ReadRequest): string {
  return JSON.stringify(ReadRequest$outboundSchema.parse(readRequest));
}
export function readRequestFromJSON(
  jsonString: string,
): SafeParseResult<ReadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadRequest' from JSON`,
  );
}
