/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e805141d88f
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SendTextMessageRequest = {
  /**
   * WhatsApp conversation address. A bare international phone number, a
   *
   * @remarks
   * phone-number JID (`@s.whatsapp.net`), a LID (`@lid`), or a group JID
   * (`@g.us`). Use the inbound webhook `chatId` unchanged when replying.
   */
  chatId: string;
  /**
   * Message text after surrounding whitespace is trimmed.
   */
  text: string;
  /**
   * Native WhatsApp/Baileys message identifier.
   */
  quoteMessageId?: string | undefined;
};

/** @internal */
export const SendTextMessageRequest$inboundSchema: z.ZodMiniType<
  SendTextMessageRequest,
  unknown
> = z.object({
  chatId: z.string(),
  text: z.string(),
  quoteMessageId: z.optional(z.string()),
});
/** @internal */
export type SendTextMessageRequest$Outbound = {
  chatId: string;
  text: string;
  quoteMessageId?: string | undefined;
};

/** @internal */
export const SendTextMessageRequest$outboundSchema: z.ZodMiniType<
  SendTextMessageRequest$Outbound,
  SendTextMessageRequest
> = z.object({
  chatId: z.string(),
  text: z.string(),
  quoteMessageId: z.optional(z.string()),
});

export function sendTextMessageRequestToJSON(
  sendTextMessageRequest: SendTextMessageRequest,
): string {
  return JSON.stringify(
    SendTextMessageRequest$outboundSchema.parse(sendTextMessageRequest),
  );
}
export function sendTextMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<SendTextMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendTextMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendTextMessageRequest' from JSON`,
  );
}
