/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 39994808b4cd
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SendMediaMessageRequest,
  SendMediaMessageRequest$inboundSchema,
  SendMediaMessageRequest$Outbound,
  SendMediaMessageRequest$outboundSchema,
} from "./send-media-message-request.js";
import {
  SendTextMessageRequest,
  SendTextMessageRequest$inboundSchema,
  SendTextMessageRequest$Outbound,
  SendTextMessageRequest$outboundSchema,
} from "./send-text-message-request.js";

/**
 * Exactly one of the text and media request variants.
 */
export type SendMessageRequest =
  | SendTextMessageRequest
  | SendMediaMessageRequest;

/** @internal */
export const SendMessageRequest$inboundSchema: z.ZodMiniType<
  SendMessageRequest,
  unknown
> = smartUnion([
  SendTextMessageRequest$inboundSchema,
  SendMediaMessageRequest$inboundSchema,
]);
/** @internal */
export type SendMessageRequest$Outbound =
  | SendTextMessageRequest$Outbound
  | SendMediaMessageRequest$Outbound;

/** @internal */
export const SendMessageRequest$outboundSchema: z.ZodMiniType<
  SendMessageRequest$Outbound,
  SendMessageRequest
> = smartUnion([
  SendTextMessageRequest$outboundSchema,
  SendMediaMessageRequest$outboundSchema,
]);

export function sendMessageRequestToJSON(
  sendMessageRequest: SendMessageRequest,
): string {
  return JSON.stringify(
    SendMessageRequest$outboundSchema.parse(sendMessageRequest),
  );
}
export function sendMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageRequest' from JSON`,
  );
}
