/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7989c853ec14
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OutboundMedia,
  OutboundMedia$inboundSchema,
  OutboundMedia$Outbound,
  OutboundMedia$outboundSchema,
} from "./outbound-media.js";

export type SendMediaMessageRequest = {
  /**
   * WhatsApp conversation address. A bare international phone number, a
   *
   * @remarks
   * phone-number JID (`@s.whatsapp.net`), a LID (`@lid`), or a group JID
   * (`@g.us`). Use the inbound webhook `chatId` unchanged when replying.
   */
  chatId: string;
  /**
   * Supply exactly one URL or base64 source.
   */
  media: OutboundMedia;
  /**
   * Native WhatsApp/Baileys message identifier.
   */
  quoteMessageId?: string | undefined;
};

/** @internal */
export const SendMediaMessageRequest$inboundSchema: z.ZodMiniType<
  SendMediaMessageRequest,
  unknown
> = z.object({
  chatId: z.string(),
  media: OutboundMedia$inboundSchema,
  quoteMessageId: z.optional(z.string()),
});
/** @internal */
export type SendMediaMessageRequest$Outbound = {
  chatId: string;
  media: OutboundMedia$Outbound;
  quoteMessageId?: string | undefined;
};

/** @internal */
export const SendMediaMessageRequest$outboundSchema: z.ZodMiniType<
  SendMediaMessageRequest$Outbound,
  SendMediaMessageRequest
> = z.object({
  chatId: z.string(),
  media: OutboundMedia$outboundSchema,
  quoteMessageId: z.optional(z.string()),
});

export function sendMediaMessageRequestToJSON(
  sendMediaMessageRequest: SendMediaMessageRequest,
): string {
  return JSON.stringify(
    SendMediaMessageRequest$outboundSchema.parse(sendMediaMessageRequest),
  );
}
export function sendMediaMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<SendMediaMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMediaMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMediaMessageRequest' from JSON`,
  );
}
