/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 766ad8727d41
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SendMessageResponse = {
  success: true;
  /**
   * Native WhatsApp/Baileys message identifier.
   */
  id: string;
};

/** @internal */
export const SendMessageResponse$inboundSchema: z.ZodMiniType<
  SendMessageResponse,
  unknown
> = z.object({
  success: z.literal(true),
  id: z.string(),
});
/** @internal */
export type SendMessageResponse$Outbound = {
  success: true;
  id: string;
};

/** @internal */
export const SendMessageResponse$outboundSchema: z.ZodMiniType<
  SendMessageResponse$Outbound,
  SendMessageResponse
> = z.object({
  success: z.literal(true),
  id: z.string(),
});

export function sendMessageResponseToJSON(
  sendMessageResponse: SendMessageResponse,
): string {
  return JSON.stringify(
    SendMessageResponse$outboundSchema.parse(sendMessageResponse),
  );
}
export function sendMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageResponse' from JSON`,
  );
}
