/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 120ff2e4ccdf
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SuccessResponse = {
  success: true;
};

/** @internal */
export const SuccessResponse$inboundSchema: z.ZodMiniType<
  SuccessResponse,
  unknown
> = z.object({
  success: z.literal(true),
});
/** @internal */
export type SuccessResponse$Outbound = {
  success: true;
};

/** @internal */
export const SuccessResponse$outboundSchema: z.ZodMiniType<
  SuccessResponse$Outbound,
  SuccessResponse
> = z.object({
  success: z.literal(true),
});

export function successResponseToJSON(
  successResponse: SuccessResponse,
): string {
  return JSON.stringify(SuccessResponse$outboundSchema.parse(successResponse));
}
export function successResponseFromJSON(
  jsonString: string,
): SafeParseResult<SuccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SuccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SuccessResponse' from JSON`,
  );
}
