/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c748e5b84b41
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TypingRequest = {
  /**
   * WhatsApp conversation address. A bare international phone number, a
   *
   * @remarks
   * phone-number JID (`@s.whatsapp.net`), a LID (`@lid`), or a group JID
   * (`@g.us`). Use the inbound webhook `chatId` unchanged when replying.
   */
  chatId: string;
};

/** @internal */
export const TypingRequest$inboundSchema: z.ZodMiniType<
  TypingRequest,
  unknown
> = z.object({
  chatId: z.string(),
});
/** @internal */
export type TypingRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const TypingRequest$outboundSchema: z.ZodMiniType<
  TypingRequest$Outbound,
  TypingRequest
> = z.object({
  chatId: z.string(),
});

export function typingRequestToJSON(typingRequest: TypingRequest): string {
  return JSON.stringify(TypingRequest$outboundSchema.parse(typingRequest));
}
export function typingRequestFromJSON(
  jsonString: string,
): SafeParseResult<TypingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypingRequest' from JSON`,
  );
}
